#ifndef SERIAL_PROTOCOL_H
#define SERIAL_PROTOCOL_H

#define PROTO_GRBL_OK "ok"
#define PROTO_GRBL_ERROR_PREFIX "error:"

#define PROTO_CLAW_CLOSE "CLAW:CLOSE"
#define PROTO_CLAW_OPEN "CLAW:OPEN"
#define PROTO_CLAW_STATUS "CLAW:STATUS?"

#define PROTO_CLAW_ACK_CLOSED "ACK:CLAW:CLOSED"
#define PROTO_CLAW_ACK_OPENED "ACK:CLAW:OPENED"
#define PROTO_CLAW_STATUS_CLOSED "STATUS:CLOSED"
#define PROTO_CLAW_STATUS_OPEN "STATUS:OPEN"

#endif
